module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        white: {
          pure: "#FFFFFF",
        },
        blue: {
          gdm: "#26B4FF",
        },
        gray: {
          navbar: "#2F3337",
          primary: "#424242",
          secondary: "#9A9A9A",
          languid: "#CBCEDD",
          gdm: "#E5E7EB",
        },
      },
      fontFamily: {
        Roboto: ["Roboto", "sans-serif"],
      },

      screens: {
        vs: "375px",
        "500media": "500px",
        md: "768px",
        "640media": "640px",
        "900media": "900px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
        "1620media": "1620px",
        "3xl": "1920px",
      },
      inset: {
        "03": "0.3rem",
        "04": "0.4rem",
        "06": "0.6rem",
        "08": "0.8rem",
        "eye-icon": "29.8px",
      },
    },
    fontSize: {
      xs: ".75rem",
      sm: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "hero-cards": "2.85rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
    screens: {},
    zIndex: {
      "-1": -1,
      "-2": -2,
      "-3": -3,
      "-4": -4,
      "-5": -5,
      "-6": -6,
      "-7": -7,
      "-8": -8,
      0: 0,
      1: 1,
      2: 2,
      10: 10,
      20: 20,
      30: 30,
      40: 40,
      50: 50,
      25: 25,
      75: 75,
      100: 100,
      auto: "auto",
    },
    backgroundSize: {
      auto: "auto",
      cover: "cover",
      contain: "contain",
      "size-3dots-icon": "0.25rem 1.25rem",
      125: "1.25rem",
    },
  },
  variants: {
    extend: {
      fontWeight: ["hover", "focus", "group-focus"],
      padding: ["hover", "group-hover"],
      borderColor: ["disabled"],
      backgroundColor: ["active", "hover", "group-hover"],
      transform: ["active"],
      scale: ["active", "group-hover"],
      visibility: ["group-hover"],
      opacity: ["disabled"],
      textColor: ["group-focus"],
      textOpacity: ["group-focus"],
      backgroundImage: ["active", "hover", "group-hover"],
    },
  },
  plugins: [],
};
